// Generated by CoffeeScript 1.4.0
(function() {
  var container, events, game, render;

  container = document.getElementById("game");

  game = new TicTacToe();

  render = function() {
    var html, msg, msgtext, row, tile, x, y, _i, _j, _len, _len1, _ref;
    html = "";
    _ref = game.board;
    for (x = _i = 0, _len = _ref.length; _i < _len; x = ++_i) {
      row = _ref[x];
      for (y = _j = 0, _len1 = row.length; _j < _len1; y = ++_j) {
        tile = row[y];
        html = "" + html + "<a href=\"#\" data-x=\"" + x + "\" data-y=\"" + y + "\" class=\"tile-" + (tile.textStatus()) + "\">";
        html = "" + html + "<span class=\"x\">X</span><span class=\"o\">O</span></a>";
      }
    }
    html = "" + html + "<div id=\"msg\" class=\"msg\"></div>";
    container.innerHTML = html;
    game.textStatus().split(' ').forEach(function(c) {
      return container.classList.add(c);
    });
    if (game.textStatus().indexOf("done") >= 0) {
      msg = document.getElementById("msg");
      switch (game.status) {
        case gamestatus.won.x:
          msgtext = "X is the winner!";
          break;
        case gamestatus.won.o:
          msgtext = "O is the winner!";
          break;
        case gamestatus.draw:
          msgtext = "It's a draw.";
      }
      msg.innerHTML = msgtext;
      return setTimeout(function() {
        game = new TicTacToe();
        container.setAttribute("class", "");
        msg.innerHTML = "";
        return render();
      }, 3000);
    } else {
      return events();
    }
  };

  events = function() {
    var node, _i, _len, _ref, _results;
    _ref = container.childNodes;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      node = _ref[_i];
      _results.push(node.addEventListener("click", function(e) {
        var data;
        e.preventDefault();
        data = this.dataset;
        game.setMove(data.x, data.y);
        return render();
      }));
    }
    return _results;
  };

  render();

}).call(this);
