// Generated by CoffeeScript 1.4.0
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  (function(window) {
    var Runner, defaultLimit, defaultRate;
    defaultRate = 10;
    defaultLimit = 10;
    Runner = (function() {

      function Runner(rate, limit) {
        this.rate = rate != null ? rate : defaultRate;
        this.limit = limit != null ? limit : defaultLimit;
        this.runner = __bind(this.runner, this);

      }

      Runner.prototype.rate = null;

      Runner.prototype.limit = null;

      Runner.prototype.queue = [];

      Runner.prototype.poll = null;

      Runner.prototype.missed = 0;

      Runner.prototype.push = function(callback) {
        this.queue.push(callback);
        if (this.poll === null) {
          return this.start();
        }
      };

      Runner.prototype.start = function() {
        return this.poll = setInterval(this.runner, this.rate);
      };

      Runner.prototype.runner = function() {
        var callback, l;
        l = this.queue.length;
        if (l > 0) {
          callback = this.queue.shift();
          return callback();
        } else if (this.missed >= this.limit) {
          this.missed = 0;
          return clearInterval(this.poll);
        } else {
          return this.missed += 1;
        }
      };

      return Runner;

    })();
    return window.Runner = Runner;
  })(window);

}).call(this);
